### ISSUE TITLE
Latest release not available on maven central repository

### ISSUE THREAD

**Issue by macrel** [ibanity/ibanity-java#117]
Hi, 

I was trying to download the JAR file for the latest release through maven central repository but it's not available. It seems like the action for this has failed > https://github.com/ibanity/ibanity-java/actions . Of course I can create the JAR myself, but just putting it out here since I noticed it failed.

**Comment by damienbr** [comment]
Hi @macrel ,

Indeed, Sonatype is experiencing outage which is blocking us from publishing the java binaries on maven central.
We have requested to be migrated to the new host which is working fine but I don't have any ETA.
We are tracking the issue https://issues.sonatype.org/browse/OSSRH-76202
(https://issues.sonatype.org/browse/OSSRH-47187)
Sorry for the inconvenience, 

Damien

**Comment by damienbr** [comment]
Fixed. We created a new release deployed on the new sonatype infrastructure.
