### ISSUE TITLE
[Q] Does the SDK take care of Idempotency?

### ISSUE THREAD

**Issue by dino-jamescauwelier** [ibanity/ibanity-java#31]
I am using the payment initiation in the SDK and see no option to provide an idempotency key.  How is idempotency handled in the SDK?  

In our case we have a microservice architecture and have a unique UUID for the payment initiation.  An integrator service accepts requests from other services to initiate a payment.  Those services behave in an at-least-once fashion in case they were unable to confirm the payment was initiated.  In case multiple attempts were made, the idempotency key needs to be passed manually by us instead of a UUID controlled by the SDK.  Is that possible currently?

**Comment by damienbr** [comment]
Hello, 

the SDK takes care of that thanks to the IdempotencyInterceptor.java class. For each POST and PATCH request, a UUID is generated and the header is added to the request.

You can pass an idempotency key in the additional headers.

At the moment, it will be replaced by the SDK but I will release a new version that won't override the existing header.

Please, make sure to use the header "banity-Idempotency-Key".

**Comment by damienbr** [comment]
It's fixed with the last release: 1.2.20190606144157.
