### ISSUE TITLE
meta authorizationPortal should not be mandatory

### ISSUE THREAD

**Issue by jluyten** [ibanity/ibanity-java#47]
According to the API when creating an account information request, the meta/authorizationPortal should not be mandatory: https://documentation.ibanity.com/xs2a/api#create-account-information-access-request

When running my PACT tests, it says it is however: Expected meta={"authorizationPortal":{}} but was missing. Furthermore, it expects it to be _inside_ the attributes object, instead of next to it:
`{
	"attributes": {
		"consentReference": "3d9afd39-e0cd-43c4-b0c0-63f5ca247ba7",
		"redirectUri": "https://some-redirect-uri.com",
		"allowFinancialInstitutionRedirectUri": false,
		"meta": {
			"authorizationPortal": {}
		},
		"requestedAccountReferences": ["BE61732540451517"]
	},
	"type": "accountInformationAccessRequest"
}`

I see two actions:
* Please fix so that meta / authorizationPortal is not mandatory
* Please fix so that meta is next to attributes and not inside attributes

**Comment by mlainez** [comment]
@damienbr can we close this?

**Comment by damienbr** [comment]
yes.
