### ISSUE TITLE
Include Request ID in IbanityException

### ISSUE THREAD

**Issue by laurent-cake** [ibanity/ibanity-java#51]
Every request to Ibanity returns with a request ID which is often asked for when there are problems. However, currently there is no way to get this info out without enabling debug logging, which is way too much info for what we need.

It would be nice if you could add the request ID as field in the IbanityException so we easily retrieve and report it.

**Comment by thibaultponcelet** [comment]
+1 @damienbr

**Comment by damienbr** [comment]
Yup, good idea. I'll add it shortly.

**Comment by damienbr** [comment]
Fix released with version 1.2.20191216102123.

**Comment by laurent-cake** [comment]
Did you release it to maven central repository? Cause I don't see it there (yet)

**Comment by damienbr** [comment]
Yes, but mirrors might take a few hours to be updated.
